### ISSUE TITLE
fixed the syntax

### ISSUE THREAD

**Issue by PashaGeronimo** [filirnd/Lede_Openwrt_Telegram_Bot#1]
./telegrambot enable - this is correct

**Comment by filirnd** [comment]
You mean this
```
cd /root/
cp telegrambot /etc/init.d/
/etc/inid.d/telegrambot enable
```
to this : 
```
cd /root/
cp telegrambot /etc/init.d/
cd /etc/init.d/
./telegrambot enable
```
or other ?

**Comment by PashaGeronimo** [comment]
yes ./telegrambot enable

**Comment by PashaGeronimo** [comment]
how do I send a command with a variable? like this  /ping goole.com
Now i use this: 
						("/pinggoogle")
							clients=$(ping google.com -w 4)
							RETURN_TEXT="$(printf "Ping google: \n$clients")"
							send_to_msg $msg_id $origin "\${RETURN_TEXT}"
                                                        ;;

**Comment by filirnd** [comment]
For your problem i think you can use somethink like this in switch case
```
case "$cmd" in
        ("/ping [a-zA-Z0-9_.-]*$")
                echo "match!!!"
      .....
esac
```
and edit this to print more parameters 
`cmd=$(echo $command |  awk '{print $1}')
`
But imho for security issues I don't set any commands with params to my server. A param can be setted like a command and someone can execute malicius code on my router :dancing_women:
